jenkins:
  systemMessage: "Spring PetClinic DevSecOps Pipeline"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              scope: GLOBAL
              id: "sonar-token"
              secret: "${SONAR_TOKEN}"
              description: "SonarQube analysis token"

unclassified:
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
      - name: "SonarQube"
        serverUrl: "http://sonarqube:9000"
        credentialsId: "sonar-token"
        triggers:
          skipScmCause: false
          skipUpstreamCause: false
  location:
    url: "http://jenkins:8080/"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - script: >
      pipelineJob('spring-petclinic') {
        triggers {
          scm('H/2 * * * *')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/treytuscai/spring-petclinic.git')
                }
                branches('*/automated')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }